/**
 * Simplified Chinese translations for the BetterOffice XLSX editor.
 *
 * The official `@betteroffice/xlsx-i18n/zh-CN` pack is an empty shell — every
 * value is `null` (community translation not yet contributed), so tooltips and
 * menus fall back to English. This module provides the full zh-CN set, keyed to
 * the same shape as the official `en` pack, and is deep-merged over the shell
 * so any future upstream translations win.
 */

import type { Translations } from '@betteroffice/xlsx-i18n';

export const XLSX_ZH_CN: Translations = {
  _lang: 'zh-CN',
  toolbar: {
    actionsLabel: '电子表格操作',
    fileActionsLabel: '文件操作',
    historyLabel: '历史记录',
    searchMenus: '搜索菜单',
    print: '打印',
    paintFormat: '格式刷',
    zoom: '缩放',
    zoomValue: '缩放：{value}',
    currency: '设置为货币格式',
    currencySymbol: '¥',
    percent: '设置为百分比格式',
    decreaseDecimal: '减少小数位数',
    increaseDecimal: '增加小数位数',
    moreNumberFormats: '更多数字格式',
    fontFamily: '字体',
    fontSize: '字号',
    decreaseFontSize: '减小字号',
    increaseFontSize: '增大字号',
    bold: '加粗',
    italic: '斜体',
    strikethrough: '删除线',
    textColor: '文字颜色',
    fillColor: '填充颜色',
    borders: '边框',
    borderColor: '边框颜色',
    mergeCells: '合并单元格',
    horizontalAlignment: '水平对齐',
    verticalAlignment: '垂直对齐',
    textWrapping: '自动换行',
    more: '更多工具栏项',
    groups: {
      search: '搜索',
      history: '历史记录',
      print: '打印',
      paintFormat: '格式刷',
      zoom: '缩放',
      number: '数字格式',
      font: '字体',
      text: '文本格式',
      colors: '颜色',
      borders: '边框',
      merge: '合并单元格',
      alignment: '对齐方式',
    },
    numberFormats: {
      automatic: '自动',
      plainText: '纯文本',
      number: '数字',
      percent: '百分比',
      scientific: '科学计数',
      currency: '货币',
      date: '日期',
      time: '时间',
      custom: '自定义数字格式…',
    },
    borderPresets: {
      all: '所有边框',
      inner: '内部边框',
      horizontal: '水平边框',
      vertical: '垂直边框',
      outer: '外边框',
      left: '左边框',
      top: '上边框',
      right: '右边框',
      bottom: '下边框',
      none: '清除边框',
    },
    borderStyles: {
      solid: '实线',
      dashed: '虚线',
      dotted: '点线',
      double: '双线',
    },
    merge: {
      all: '合并全部',
      horizontal: '水平合并',
      vertical: '垂直合并',
      unmerge: '取消合并',
    },
    horizontalAlign: {
      left: '左对齐',
      center: '居中',
      right: '右对齐',
    },
    verticalAlign: {
      top: '顶端对齐',
      middle: '垂直居中',
      bottom: '底端对齐',
    },
    wrapping: {
      overflow: '溢出',
      wrap: '自动换行',
      clip: '裁剪',
    },
    formulaBarLabel: '公式栏',
    nameBoxPlaceholder: '名称框',
    formulaPlaceholder: '输入值或公式',
    save: '保存',
    exportPng: '导出 PNG',
    undo: '撤销',
    redo: '重做',
  },
  editor: {
    appLabel: '电子表格编辑器',
    demoCellText: 'OpenOOXML xlsx',
    openError: '无法打开此工作簿',
    sheetTabsLabel: '工作表',
  },
  proposals: {
    panelLabel: '智能体建议',
    empty: '暂无待处理的建议',
    cellCount: '{count, plural, one {# 个单元格} other {# 个单元格}}',
    changeArrow: '→',
    accept: '接受',
    reject: '拒绝',
    forceApply: '强制应用',
    staleWarning: '此建议基于较早的数据',
  },
  a11y: {
    gridLabel: '电子表格网格',
    rowHeaderLabel: '第 {row} 行',
    columnHeaderLabel: '第 {column} 列',
    cellLabel: '{address}，{value}',
    cellLabelSelected: '{address}，{value}，已选中',
    emptyCellLabel: '{address}，空',
    emptyCellLabelSelected: '{address}，空，已选中',
  },
};
